# vim: expandtab tabstop=2 shiftwidth=2
name: Test iTunes Header Server

env:
  PYTHONIOENCODING: utf-8

on: 
  push:
  workflow_dispatch:
    inputs:
      itunes_debug_enabled:
        description: 'Run the build with iTunes ngrok-RDP debugging enabled'
        required: false
        default: false
      test_debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  repository_dispatch:

jobs:
  header_server:
    name: 'Test Setup'
    runs-on: "windows-latest"
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
      - name: Setup iTunes
        uses: NyaMisty/actions-iTunes-header@master
        with:
          apple_id: ${{ secrets.APPLEID }}
          apple_id_pwd: ${{ secrets.APPLEID_PWD }}
          ngrok_token: ${{ secrets.NGROK_AUTH_TOKEN }}
      
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.test_debug_enabled }}
      #   env:
      #     SECRETS_CONTEXT: ${{ toJson(secrets) }}
        
      - name: Test iTunes Server
        run: |
            curl -vv 127.0.0.1:9000
      
      - uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        if: ${{ always() && github.event_name == 'workflow_dispatch' && github.event.inputs.test_debug_enabled }}
        with:
          ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          password: Aa123456
          foreground: false